name: Train Model

on:
  push:
    branches:
      - main

jobs:
  train:
    name: Train Model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train model
        run: python train.py
      - name: Deploy Model for inference
        run: deploy.py
